/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * 123
 * OpenAPI spec version: 1.0
 */
import type { AddMemberToWorkspaceDtoRole } from './addMemberToWorkspaceDtoRole';

export interface AddMemberToWorkspaceDto {
  userId: string;
  workspaceId: string;
  role: AddMemberToWorkspaceDtoRole;
}
