/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * 123
 * OpenAPI spec version: 1.0
 */

export type AddMemberToWorkspaceDtoRole = typeof AddMemberToWorkspaceDtoRole[keyof typeof AddMemberToWorkspaceDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddMemberToWorkspaceDtoRole = {
  READER: 'READER',
  REGULAR: 'REGULAR',
  ADMIN: 'ADMIN',
  SUPERADMIN: 'SUPERADMIN',
} as const;
