/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetHealth200Info } from './appControllerGetHealth200Info';
import type { AppControllerGetHealth200Error } from './appControllerGetHealth200Error';
import type { AppControllerGetHealth200Details } from './appControllerGetHealth200Details';

export type AppControllerGetHealth200 = {
  status?: string;
  /** @nullable */
  info?: AppControllerGetHealth200Info;
  /** @nullable */
  error?: AppControllerGetHealth200Error;
  details?: AppControllerGetHealth200Details;
};
