/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetHealth503Info } from './appControllerGetHealth503Info';
import type { AppControllerGetHealth503Error } from './appControllerGetHealth503Error';
import type { AppControllerGetHealth503Details } from './appControllerGetHealth503Details';

export type AppControllerGetHealth503 = {
  status?: string;
  /** @nullable */
  info?: AppControllerGetHealth503Info;
  /** @nullable */
  error?: AppControllerGetHealth503Error;
  details?: AppControllerGetHealth503Details;
};
