/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */

export type CreateMicroserviceDtoType = typeof CreateMicroserviceDtoType[keyof typeof CreateMicroserviceDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMicroserviceDtoType = {
  URL: 'URL',
  TEXT: 'TEXT',
} as const;
