/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * 123
 * OpenAPI spec version: 1.0
 */

export interface CreateProjectDto {
  name: string;
  emoji: string;
  description: string;
  workspaceId: string;
}
