/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * 123
 * OpenAPI spec version: 1.0
 */
import type { CreateMicroserviceDtoType } from './createMicroserviceDtoType';

export interface CreateMicroserviceDto {
  name: string;
  type: CreateMicroserviceDtoType;
  content: string;
  projectId: string;
}
