/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * 123
 * OpenAPI spec version: 1.0
 */

export type CreateMicroserviceDtoType = typeof CreateMicroserviceDtoType[keyof typeof CreateMicroserviceDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMicroserviceDtoType = {
  URL: 'URL',
  TEXT: 'TEXT',
} as const;
