/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */
import type { GetProfileResponseDtoRole } from './getProfileResponseDtoRole';

export interface GetProfileResponseDto {
  id: string;
  email: string;
  displayName: string;
  picture: string;
  role: GetProfileResponseDtoRole;
  isVerified: boolean;
  isTwoFactorEnabled: boolean;
  method: string;
  createdAt: string;
  updatedAt: string;
}
