/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  name: string;
  email: string;
  isTwoFactorEnabled: boolean;
}
