/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */
import type { FindAllWorkspaceResponseDto } from './findAllWorkspaceResponseDto';

export type WorkspaceControllerFindAll200AllOf = {
  data?: FindAllWorkspaceResponseDto;
};
