/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */
import type { BaseResponse } from './baseResponse';
import type { WorkspaceControllerFindAll200AllOf } from './workspaceControllerFindAll200AllOf';

export type WorkspaceControllerFindAll200 = BaseResponse & WorkspaceControllerFindAll200AllOf;
