/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Swagger Provider Documentation
 * Сервис для объединения Swagger схем в одном месте
 * OpenAPI spec version: 1.0
 */
import type { BaseResponse } from './baseResponse';
import type { WorkspaceControllerFindOne200AllOf } from './workspaceControllerFindOne200AllOf';

export type WorkspaceControllerFindOne200 = BaseResponse & WorkspaceControllerFindOne200AllOf;
